<a href="https://colab.research.google.com/github/gonzo1978/CAP4453/blob/main/backprop_step_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

# input
x = torch.tensor([[1.1, 0.4]])

# parameters
w1=  torch.tensor([[0.3, -0.3],[-0.4, 0.6]],requires_grad=True)
w2=  torch.tensor([[0.9],[0.3]],requires_grad=True)

# groundtruth
labels = torch.tensor([[1]])

# layer 1
z1 = torch.tanh(torch.mm(x, w1)) 

# layer 2
z2 = torch.sigmoid(torch.mm(z1, w2)) 

print(z1)
print(z2)

loss = (z2-labels)*(z2-labels)/2
cost = loss.mean()
loss.backward()

print('loss: ' + str(loss))
print('cost: ' + str(cost))

print(w1.grad)
print(w2.grad)


tensor([[ 0.1684, -0.0898]], grad_fn=<TanhBackward0>)
tensor([[0.5311]], grad_fn=<SigmoidBackward0>)
loss: tensor([[0.1099]], grad_fn=<DivBackward0>)
cost: tensor(0.1099, grad_fn=<MeanBackward0>)
tensor([[-0.1123, -0.0382],
        [-0.0408, -0.0139]])
tensor([[-0.0197],
        [ 0.0105]])
